=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.503.5

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

module Plaid
  VERSION = '26.0.1'
end
