=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.688.6

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module Plaid
  # Metadata about the CRA Credit Profile Report.
  class CraCreditProfileReportMetadata
    # The number of items used to calculate the report.
    attr_accessor :item_count

    # The institution IDs associated with the report.
    attr_accessor :institution_ids

    # The total number of accounts in the report.
    attr_accessor :account_count

    # The number of primary accounts in the report.
    attr_accessor :primary_account_count

    # The number of depository accounts in the report.
    attr_accessor :depository_account_type_count

    # The number of credit accounts in the report.
    attr_accessor :credit_account_type_count

    # The number of other accounts in the report.
    attr_accessor :other_account_type_count

    # The number of accounts with multiple owners in the report.
    attr_accessor :multiple_owner_account_count

    # The time when the report was generated.
    attr_accessor :generated_at

    # The date of the oldest transaction in the report.
    attr_accessor :oldest_transaction_date

    # The date of the most recent transaction in the report.
    attr_accessor :most_recent_transaction_date

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'item_count' => :'item_count',
        :'institution_ids' => :'institution_ids',
        :'account_count' => :'account_count',
        :'primary_account_count' => :'primary_account_count',
        :'depository_account_type_count' => :'depository_account_type_count',
        :'credit_account_type_count' => :'credit_account_type_count',
        :'other_account_type_count' => :'other_account_type_count',
        :'multiple_owner_account_count' => :'multiple_owner_account_count',
        :'generated_at' => :'generated_at',
        :'oldest_transaction_date' => :'oldest_transaction_date',
        :'most_recent_transaction_date' => :'most_recent_transaction_date'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'item_count' => :'Integer',
        :'institution_ids' => :'Array<String>',
        :'account_count' => :'Integer',
        :'primary_account_count' => :'Integer',
        :'depository_account_type_count' => :'Integer',
        :'credit_account_type_count' => :'Integer',
        :'other_account_type_count' => :'Integer',
        :'multiple_owner_account_count' => :'Integer',
        :'generated_at' => :'Time',
        :'oldest_transaction_date' => :'Date',
        :'most_recent_transaction_date' => :'Date'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Plaid::CraCreditProfileReportMetadata` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Plaid::CraCreditProfileReportMetadata`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'item_count')
        self.item_count = attributes[:'item_count']
      end

      if attributes.key?(:'institution_ids')
        if (value = attributes[:'institution_ids']).is_a?(Array)
          self.institution_ids = value
        end
      end

      if attributes.key?(:'account_count')
        self.account_count = attributes[:'account_count']
      end

      if attributes.key?(:'primary_account_count')
        self.primary_account_count = attributes[:'primary_account_count']
      end

      if attributes.key?(:'depository_account_type_count')
        self.depository_account_type_count = attributes[:'depository_account_type_count']
      end

      if attributes.key?(:'credit_account_type_count')
        self.credit_account_type_count = attributes[:'credit_account_type_count']
      end

      if attributes.key?(:'other_account_type_count')
        self.other_account_type_count = attributes[:'other_account_type_count']
      end

      if attributes.key?(:'multiple_owner_account_count')
        self.multiple_owner_account_count = attributes[:'multiple_owner_account_count']
      end

      if attributes.key?(:'generated_at')
        self.generated_at = attributes[:'generated_at']
      end

      if attributes.key?(:'oldest_transaction_date')
        self.oldest_transaction_date = attributes[:'oldest_transaction_date']
      end

      if attributes.key?(:'most_recent_transaction_date')
        self.most_recent_transaction_date = attributes[:'most_recent_transaction_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @item_count.nil?
        invalid_properties.push('invalid value for "item_count", item_count cannot be nil.')
      end

      if @institution_ids.nil?
        invalid_properties.push('invalid value for "institution_ids", institution_ids cannot be nil.')
      end

      if @account_count.nil?
        invalid_properties.push('invalid value for "account_count", account_count cannot be nil.')
      end

      if @primary_account_count.nil?
        invalid_properties.push('invalid value for "primary_account_count", primary_account_count cannot be nil.')
      end

      if @depository_account_type_count.nil?
        invalid_properties.push('invalid value for "depository_account_type_count", depository_account_type_count cannot be nil.')
      end

      if @credit_account_type_count.nil?
        invalid_properties.push('invalid value for "credit_account_type_count", credit_account_type_count cannot be nil.')
      end

      if @other_account_type_count.nil?
        invalid_properties.push('invalid value for "other_account_type_count", other_account_type_count cannot be nil.')
      end

      if @multiple_owner_account_count.nil?
        invalid_properties.push('invalid value for "multiple_owner_account_count", multiple_owner_account_count cannot be nil.')
      end

      if @generated_at.nil?
        invalid_properties.push('invalid value for "generated_at", generated_at cannot be nil.')
      end

      if @oldest_transaction_date.nil?
        invalid_properties.push('invalid value for "oldest_transaction_date", oldest_transaction_date cannot be nil.')
      end

      if @most_recent_transaction_date.nil?
        invalid_properties.push('invalid value for "most_recent_transaction_date", most_recent_transaction_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @item_count.nil?
      return false if @institution_ids.nil?
      return false if @account_count.nil?
      return false if @primary_account_count.nil?
      return false if @depository_account_type_count.nil?
      return false if @credit_account_type_count.nil?
      return false if @other_account_type_count.nil?
      return false if @multiple_owner_account_count.nil?
      return false if @generated_at.nil?
      return false if @oldest_transaction_date.nil?
      return false if @most_recent_transaction_date.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          item_count == o.item_count &&
          institution_ids == o.institution_ids &&
          account_count == o.account_count &&
          primary_account_count == o.primary_account_count &&
          depository_account_type_count == o.depository_account_type_count &&
          credit_account_type_count == o.credit_account_type_count &&
          other_account_type_count == o.other_account_type_count &&
          multiple_owner_account_count == o.multiple_owner_account_count &&
          generated_at == o.generated_at &&
          oldest_transaction_date == o.oldest_transaction_date &&
          most_recent_transaction_date == o.most_recent_transaction_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [item_count, institution_ids, account_count, primary_account_count, depository_account_type_count, credit_account_type_count, other_account_type_count, multiple_owner_account_count, generated_at, oldest_transaction_date, most_recent_transaction_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Plaid.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
