=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.681.5

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module Plaid
  # Object containing information on contribution transactions for the 401k account. Note that the sum fields in this object represent the total of absolute contribution values.
  class InvestmentsAuth401kContributionDetails
    # A list of the most recent contribution transactions for the 401k account. Includes all contributions made on the same day.
    attr_accessor :last_contribution_transactions

    # Number of contribution transactions on this account, for the past month.
    attr_accessor :contribution_count_1m

    # Sum of the contribution transactions on this account, for the past month.
    attr_accessor :contribution_amount_1m

    # Number of contribution transactions on this account, for the past 6 months.
    attr_accessor :contribution_count_6m

    # Sum of the contribution transactions on this account, for the past 6 months.
    attr_accessor :contribution_amount_6m

    # Number of contribution transactions on this account, for the past 12 months.
    attr_accessor :contribution_count_12m

    # Sum of the contribution transactions on this account, for the past 12 months.
    attr_accessor :contribution_amount_12m

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'last_contribution_transactions' => :'last_contribution_transactions',
        :'contribution_count_1m' => :'contribution_count_1m',
        :'contribution_amount_1m' => :'contribution_amount_1m',
        :'contribution_count_6m' => :'contribution_count_6m',
        :'contribution_amount_6m' => :'contribution_amount_6m',
        :'contribution_count_12m' => :'contribution_count_12m',
        :'contribution_amount_12m' => :'contribution_amount_12m'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'last_contribution_transactions' => :'Array<InvestmentTransaction>',
        :'contribution_count_1m' => :'Integer',
        :'contribution_amount_1m' => :'Float',
        :'contribution_count_6m' => :'Integer',
        :'contribution_amount_6m' => :'Float',
        :'contribution_count_12m' => :'Integer',
        :'contribution_amount_12m' => :'Float'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Plaid::InvestmentsAuth401kContributionDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Plaid::InvestmentsAuth401kContributionDetails`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'last_contribution_transactions')
        if (value = attributes[:'last_contribution_transactions']).is_a?(Array)
          self.last_contribution_transactions = value
        end
      end

      if attributes.key?(:'contribution_count_1m')
        self.contribution_count_1m = attributes[:'contribution_count_1m']
      end

      if attributes.key?(:'contribution_amount_1m')
        self.contribution_amount_1m = attributes[:'contribution_amount_1m']
      end

      if attributes.key?(:'contribution_count_6m')
        self.contribution_count_6m = attributes[:'contribution_count_6m']
      end

      if attributes.key?(:'contribution_amount_6m')
        self.contribution_amount_6m = attributes[:'contribution_amount_6m']
      end

      if attributes.key?(:'contribution_count_12m')
        self.contribution_count_12m = attributes[:'contribution_count_12m']
      end

      if attributes.key?(:'contribution_amount_12m')
        self.contribution_amount_12m = attributes[:'contribution_amount_12m']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @last_contribution_transactions.nil?
        invalid_properties.push('invalid value for "last_contribution_transactions", last_contribution_transactions cannot be nil.')
      end

      if @contribution_count_1m.nil?
        invalid_properties.push('invalid value for "contribution_count_1m", contribution_count_1m cannot be nil.')
      end

      if @contribution_amount_1m.nil?
        invalid_properties.push('invalid value for "contribution_amount_1m", contribution_amount_1m cannot be nil.')
      end

      if @contribution_count_6m.nil?
        invalid_properties.push('invalid value for "contribution_count_6m", contribution_count_6m cannot be nil.')
      end

      if @contribution_amount_6m.nil?
        invalid_properties.push('invalid value for "contribution_amount_6m", contribution_amount_6m cannot be nil.')
      end

      if @contribution_count_12m.nil?
        invalid_properties.push('invalid value for "contribution_count_12m", contribution_count_12m cannot be nil.')
      end

      if @contribution_amount_12m.nil?
        invalid_properties.push('invalid value for "contribution_amount_12m", contribution_amount_12m cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @last_contribution_transactions.nil?
      return false if @contribution_count_1m.nil?
      return false if @contribution_amount_1m.nil?
      return false if @contribution_count_6m.nil?
      return false if @contribution_amount_6m.nil?
      return false if @contribution_count_12m.nil?
      return false if @contribution_amount_12m.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          last_contribution_transactions == o.last_contribution_transactions &&
          contribution_count_1m == o.contribution_count_1m &&
          contribution_amount_1m == o.contribution_amount_1m &&
          contribution_count_6m == o.contribution_count_6m &&
          contribution_amount_6m == o.contribution_amount_6m &&
          contribution_count_12m == o.contribution_count_12m &&
          contribution_amount_12m == o.contribution_amount_12m
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [last_contribution_transactions, contribution_count_1m, contribution_amount_1m, contribution_count_6m, contribution_amount_6m, contribution_count_12m, contribution_amount_12m].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Plaid.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
