=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.762.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module Plaid
  # Contains details about a line of credit account.
  class LineOfCreditLiability
    # The ID of the account that this liability belongs to.
    attr_accessor :account_id

    attr_accessor :interest_rate

    # The maximum amount of credit available on the account.
    attr_accessor :credit_limit

    # The amount of credit currently available on the account.
    attr_accessor :available_credit

    # The outstanding principal balance on the account.
    attr_accessor :principal_balance

    # The minimum payment due for the next billing cycle.
    attr_accessor :minimum_payment_amount

    # The amount of the next scheduled payment.
    attr_accessor :next_payment_amount

    # The due date of the next payment, in ISO 8601 format (YYYY-MM-DD).
    attr_accessor :next_payment_due_date

    # The amount of the most recent payment.
    attr_accessor :last_payment_amount

    # The date of the most recent payment, in ISO 8601 format (YYYY-MM-DD).
    attr_accessor :last_payment_date

    # The total amount owed as of the last statement issued.
    attr_accessor :last_statement_balance

    # The date of the last statement, in ISO 8601 format (YYYY-MM-DD).
    attr_accessor :last_statement_issue_date

    # The amount of the payment that is currently past due.
    attr_accessor :past_due_amount

    # The finance charges assessed on the account.
    attr_accessor :finance_charges

    # The date on which the draw period ends, in ISO 8601 format (YYYY-MM-DD).
    attr_accessor :draw_period_end_date

    # The various interest rates that apply to the account.
    attr_accessor :aprs

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'account_id' => :'account_id',
        :'interest_rate' => :'interest_rate',
        :'credit_limit' => :'credit_limit',
        :'available_credit' => :'available_credit',
        :'principal_balance' => :'principal_balance',
        :'minimum_payment_amount' => :'minimum_payment_amount',
        :'next_payment_amount' => :'next_payment_amount',
        :'next_payment_due_date' => :'next_payment_due_date',
        :'last_payment_amount' => :'last_payment_amount',
        :'last_payment_date' => :'last_payment_date',
        :'last_statement_balance' => :'last_statement_balance',
        :'last_statement_issue_date' => :'last_statement_issue_date',
        :'past_due_amount' => :'past_due_amount',
        :'finance_charges' => :'finance_charges',
        :'draw_period_end_date' => :'draw_period_end_date',
        :'aprs' => :'aprs'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'account_id' => :'String',
        :'interest_rate' => :'LoanInterestRate',
        :'credit_limit' => :'Float',
        :'available_credit' => :'Float',
        :'principal_balance' => :'Float',
        :'minimum_payment_amount' => :'Float',
        :'next_payment_amount' => :'Float',
        :'next_payment_due_date' => :'Date',
        :'last_payment_amount' => :'Float',
        :'last_payment_date' => :'Date',
        :'last_statement_balance' => :'Float',
        :'last_statement_issue_date' => :'Date',
        :'past_due_amount' => :'Float',
        :'finance_charges' => :'Float',
        :'draw_period_end_date' => :'Date',
        :'aprs' => :'Array<APR>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'interest_rate',
        :'credit_limit',
        :'available_credit',
        :'principal_balance',
        :'minimum_payment_amount',
        :'next_payment_amount',
        :'next_payment_due_date',
        :'last_payment_amount',
        :'last_payment_date',
        :'last_statement_balance',
        :'last_statement_issue_date',
        :'past_due_amount',
        :'finance_charges',
        :'draw_period_end_date',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `Plaid::LineOfCreditLiability` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `Plaid::LineOfCreditLiability`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'interest_rate')
        self.interest_rate = attributes[:'interest_rate']
      end

      if attributes.key?(:'credit_limit')
        self.credit_limit = attributes[:'credit_limit']
      end

      if attributes.key?(:'available_credit')
        self.available_credit = attributes[:'available_credit']
      end

      if attributes.key?(:'principal_balance')
        self.principal_balance = attributes[:'principal_balance']
      end

      if attributes.key?(:'minimum_payment_amount')
        self.minimum_payment_amount = attributes[:'minimum_payment_amount']
      end

      if attributes.key?(:'next_payment_amount')
        self.next_payment_amount = attributes[:'next_payment_amount']
      end

      if attributes.key?(:'next_payment_due_date')
        self.next_payment_due_date = attributes[:'next_payment_due_date']
      end

      if attributes.key?(:'last_payment_amount')
        self.last_payment_amount = attributes[:'last_payment_amount']
      end

      if attributes.key?(:'last_payment_date')
        self.last_payment_date = attributes[:'last_payment_date']
      end

      if attributes.key?(:'last_statement_balance')
        self.last_statement_balance = attributes[:'last_statement_balance']
      end

      if attributes.key?(:'last_statement_issue_date')
        self.last_statement_issue_date = attributes[:'last_statement_issue_date']
      end

      if attributes.key?(:'past_due_amount')
        self.past_due_amount = attributes[:'past_due_amount']
      end

      if attributes.key?(:'finance_charges')
        self.finance_charges = attributes[:'finance_charges']
      end

      if attributes.key?(:'draw_period_end_date')
        self.draw_period_end_date = attributes[:'draw_period_end_date']
      end

      if attributes.key?(:'aprs')
        if (value = attributes[:'aprs']).is_a?(Array)
          self.aprs = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if @account_id.nil?
        invalid_properties.push('invalid value for "account_id", account_id cannot be nil.')
      end

      if @aprs.nil?
        invalid_properties.push('invalid value for "aprs", aprs cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if @account_id.nil?
      return false if @aprs.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          account_id == o.account_id &&
          interest_rate == o.interest_rate &&
          credit_limit == o.credit_limit &&
          available_credit == o.available_credit &&
          principal_balance == o.principal_balance &&
          minimum_payment_amount == o.minimum_payment_amount &&
          next_payment_amount == o.next_payment_amount &&
          next_payment_due_date == o.next_payment_due_date &&
          last_payment_amount == o.last_payment_amount &&
          last_payment_date == o.last_payment_date &&
          last_statement_balance == o.last_statement_balance &&
          last_statement_issue_date == o.last_statement_issue_date &&
          past_due_amount == o.past_due_amount &&
          finance_charges == o.finance_charges &&
          draw_period_end_date == o.draw_period_end_date &&
          aprs == o.aprs
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [account_id, interest_rate, credit_limit, available_credit, principal_balance, minimum_payment_amount, next_payment_amount, next_payment_due_date, last_payment_amount, last_payment_date, last_statement_balance, last_statement_issue_date, past_due_amount, finance_charges, draw_period_end_date, aprs].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = Plaid.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
