=begin
#The Plaid API

#The Plaid REST API. Please see https://plaid.com/docs/api for more details.

The version of the OpenAPI document: 2020-09-14_1.729.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'date'
require 'time'

module Plaid
  class SandboxCraServicingSimulateErrorWebhookCode
    USER_NOT_FOUND = "USER_NOT_FOUND".freeze
    PRODUCT_GENERATION_FAILED = "PRODUCT_GENERATION_FAILED".freeze
    UNMATCH = "UNMATCH".freeze
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE".freeze
    NO_ELIGIBLE_ITEMS_ON_PROFILE = "NO_ELIGIBLE_ITEMS_ON_PROFILE".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      # We do not validate that the value is one of the enums set in the OpenAPI
      # file because we want to be able to add to our list of enums without
      # breaking this client library.
      value
    end
  end

end
